Fix mismatched C char type
The current implementation of the apr-rs library uses i8 wherever
interoperability with C's char type is expected. This works fine on
architectures like x86_64 where char is signed.

However, while building on arm64, there is an error due to type
mismatch. Excerpt from build log:

error[E0308]: mismatched types
  --> src/date.rs:18:60
   |
18 |     let rv = unsafe { crate::generated::apr_date_parse_rfc(data.as_ptr() as *const i8) };
   |                       ------------------------------------ ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
   |                       |
   |                       arguments to this function are incorrect
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`
note: function defined here
  --> /usr/share/cargo/registry/apr-0.1.9/target/aarch64-unknown-linux-gnu/debug/build/apr-31713c0a7d8c7f0e/out/generated.rs:3:154706
   |
3  | ...would be out of range or if the date is invalid."] pub fn apr_date_parse_rfc (date : * const :: std :: os :: raw :: c_char) -> apr_tim...
   |                                                              ^^^^^^^^^^^^^^^^^^

The full build log on debian:sid can be found at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068170

This arises because on arm64, ppc64el, riscv64 and s390x, C's char type
is unsigned (u8).

To remedy this, the std::ffi::c_char type is used instead of i8
wherever char values are expected. This type uses the architecture
specific implementation of the C char type.

Signed-off-by: Arnav Kohli <arnav.kohli@arm.com>